apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "${{ values.repoName }}-pipeline-autocreated"
  namespace: "openshift-gitops"
spec:
  ignoreDifferences:
  - group: "*"
    kind: ServiceAccount
    jsonPointers:
    - /imagePullSecrets
    - /secrets
  destination:
    namespace: "${{ values.repoName }}-pipelines"
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: "https://github.com/poc-examples/charts"
    path: "standard-pipeline"
    targetRevision: HEAD
    # helm:
    #   valuesObject:
    #     host: "{{ openshift.domain }}"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: "openshift-gitops"
    syncOptions:
      - CreateNamespace=true
      - Validate=false
      - SkipDryRunOnMissingResource=true
