apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "${{ values.repoName }}-pipeline-sp"
  namespace: "openshift-gitops"
spec:
  ignoreDifferences:
  - group: "*"
    kind: ServiceAccount
    jsonPointers:
    - /imagePullSecrets
    - /secrets
  destination:
    namespace: "${{ values.repoName }}-pipeline"
    server: 'https://kubernetes.default.svc'
  source:
    chart: pipeline
    repoURL: "https://poc-examples.github.io/charts"
    version: v3
    targetRevision: 0.1.7
    helm:
      valuesObject:
        targetNamespace: "${{ values.repoName }}-pipeline"
        gitAddress: "${{ values.gitAddress }}"
        username: "root"
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: "openshift-gitops"
    syncOptions:
      - CreateNamespace=true
      - Validate=false
      - SkipDryRunOnMissingResource=true
