---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: image-pipeline-trigger-template
spec:
  params:
    - name: gitrevision
      description: The git revision sha
    - name: image 
      description: The image to build and push
    - name: registry_hostname
      description: The hostname for the image registry
    - name: registry_namespace 
      description: The registry namespace for the container image
    - name: git_repo
      description: The git repository to clone
  resourcetemplates: 
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun 
      metadata: 
        name: $(tt.params.image)-container-build-$(tt.params.gitrevision)
        namespace: openshift-pipelines
      spec:
        serviceAccountName: openshift-pipelines-sa
        pipelineRef: 
          name: container-build-pipeline
        params: 
          - name: IMAGE_NAME
            value: $(tt.params.image)
          - name: REGISTRY_HOSTNAME
            value: $(tt.params.registry_hostname)
          - name: REGISTRY_NAMESPACE
            value: $(tt.params.registry_namespace)
          - name: IMAGE_TAG
            value: $(tt.params.gitrevision)
          - name: GITHUB_REPO
            value: $(tt.params.git_repo)
          - name: GITHUB_BRANCH
            value: 'main'
        podTemplate:
          securityContext:
            runAsUser: 1001
            fsGroup: 65532
        workspaces:
        - name: source
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
        - name: containers
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: gitlab-binding
spec:
  params:
    - name: gitrevision
      value: "$(body.after)"
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener: github-event-listener
  name: tekton
spec:
  port:
    targetPort: http-listener
  tls:
    termination: edge
  to:
    kind: Service
    name: el-github-event-listener
    weight: 100
  wildcardPolicy: None
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: pipeline-event-listener
spec:
  serviceAccountName: pipeline-service-account
  triggers:
    - name: filter-events
      interceptors:
        - ref:
            name: "gitlab"
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev
          params:
            - name: "eventTypes"
              value: ["Push Hook"]
        - ref:
            name: cel
          params:
          - name: "overlays"
            value:
            - key: truncated_sha
              expression: "body.after.truncate(7)"
    - name: push-event
      bindings:
        - name: gitrevision
          value: $(extensions.truncated_sha)
        - name: image
          value: "chat-window"
        - name: registry_hostname
          value: "default-route-openshift-image-registry.apps.xr42gryb.eastus.aroapp.io" 
        - name: git_repo
          value: 'https://gitlab.apps.xr42gryb.eastus.aroapp.io/root/container-library.git'
        - name: registry_namespace
          value: 'pipelines'
      template:
        ref: image-pipeline-trigger-template
