apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workshop-orchestrator
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
spec:
  goTemplate: true
  goTemplateOptions:
    - "missingkey=error"
  generators:
    - list:
        elements:
          - application: workshop-rollout-controller
            namespace: openshift-gitops
            project: controllers
            wave: "-2"
            source:
              chart: rollout-controller
              targetRevision: "0.6.62"
              repoURL: https://poc-examples.github.io/charts
            values: |
              devspaces:
                enabled: true
              # minio:
              #   enabled: true
              # serverless: 
              #   enabled: true
              # amq:
              #   enabled: true
              # opentelemetry:
              #   enabled: true
          - application: self-service-services
            namespace: openshift-gitops
            project: self-service
            wave: "-1"
            source:
              repoURL: "${{ values.gitlabRemoteUrl }}.git"
              targetRevision: "${{ values.gitlabBranch }}"
              path: "services"
              directory:
                recurse: true
          - application: self-service-applications
            namespace: openshift-gitops
            project: self-service
            wave: "-1"
            source:
              repoURL: "${{ values.gitlabRemoteUrl }}.git"
              targetRevision: "${{ values.gitlabBranch }}"
              path: "applications"
              directory:
                recurse: true
  template:
    metadata:
      name: "{{ `{{ .application }}` }}"
      annotations:
        argocd.argoproj.io/sync-wave: "{{ `{{ .wave }}` }}"
      labels:
        backstage-name: workshop-repository
    spec:
      destination:
        namespace: "{{ `{{ .namespace }}` }}"
        server: "https://kubernetes.default.svc"
      source:
        chart: "{{ `{{ .chart.name }}` }}"
        targetRevision: "{{ `{{ .chart.version }}` }}"
        repoURL: "{{ `{{ .chart.url }}` }}"
      project: "{{ `{{ .project }}` }}"
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
        syncOptions:
          - CreateNamespace=true
          - Validate=false
  templatePatch: |
    spec:
      source:
        {{ `{{- .source | nindent 8 }}` }}
        helm:
        {{ `{{- if (index . "values") }}` }}
          values: |
            {{ `{{- .values | nindent 12 }}` }}
        {{ `{{- end }}` }}
