apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: data-workbench
  title: Red Hat OpenShift AI - Workbench
  description: |
    This template automates the provisioning of a Workbench in Red Hat OpenShift AI. It provides a 
    structured environment for data scientists and developers to build, test, and deploy AI models 
    seamlessly within OpenShift AI. The template sets up the required infrastructure for AI workloads, 
    including workbenches for collaborative experimentation, model training, and integration with other 
    AI services. Teams can leverage this workbench for streamlined AI development with built-in support 
    for continuous integration and deployment through ArgoCD.
  tags:
    - openshift-ai
    - workbench
    - automation
    - data-science
    - ai-workloads
    - gitlab
    - argocd

spec:
  owner: data-science
  system: self-service
  type: Workbench
  parameters:
                
    - title: Workbench Settings
      ui:group: data-workbench
      required:
        - rootSelfServiceRepo
        - projectName
        - dataConnectorName
        - workbenchName
        - storageSize
      properties:
        rootSelfServiceRepo:
          title: Root Self-Service Repository
          type: string
          description: The root self-service repository that contains artifact deployment configurations.
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              - kind: Component
                spec.type: self-service
        projectName:
          title: Project Name
          type: string
          description: The project where the data connector is integrated.
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              - kind: Component
                spec.type: data-science-project
        dataConnectorName:
          title: Data Connector Name
          type: string
          description: The name of the data connector.
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              - kind: Component
                spec.type: data-connector
        enableCUDA:
          title: Enable CUDA
          description: Enables CUDA support for Workbench.
          default: "false"
          enum:
            - "true"
            - "false"
          type: string
        numGPU:
          title: Number of GPUs
          description: Set the number of GPUs to be allocated to the Workbench.
          default: 0
          type: number
          enum:
            - 0
            - 1
            - 2
            - 3
            - 4
        workbenchName:
          title: Workbench Name
          description: The name of the workbench.
          type: string
          pattern: "^[a-z][a-z0-9-]+$"
          minLength: 3
          maxLength: 30
        storageSize:
          title: Storage Size
          description: The storage size of the workbench working directory.
          default: "100Gi"
          type: string
          pattern: "^[0-9]+[KMGTP]i$"
          minLength: 3
          maxLength: 6

  steps:

    #################
    ## Fetch Entities
    #################

    - action: catalog:fetch
      id: fetchSelfServiceEntity
      name: Fetch Root Self-Service Repo Entity
      input:
        entityRef: ${{ parameters.rootSelfServiceRepo }}

    ###########################
    ## Template the Application
    ###########################
    - id: applicationTemplate
      name: Template Helm Application
      action: fetch:template
      input:
        url: "../../../../skeletons/applications/helm/"
        targetPath: "projects/${{ parameters.projectName | parseEntityRef | pick('name') }}/"
        values:
          repoName: "${{ parameters.workbenchName }}-workbench"
          namespace: "${{ parameters.projectName | parseEntityRef | pick('name') }}"
          chart:
            name: "data-workbench"
            chartUrl: "https://poc-examples.github.io/supporting-charts"
            chartVersion: "0.1.19"
          projectName: "${{ parameters.projectName | parseEntityRef | pick('name') }}"
          automated:
            prune: true
            selfHeal: true
          createNamespace: "true"
          valuesObject: |
            domain: ${{ steps['fetchSelfServiceEntity'].output.entity.spec.argocd.cluster }}
            user: cluster-admin
            namespace: "${{ parameters.projectName | parseEntityRef | pick('name') }}"
            notebookName: "${{ parameters.workbenchName }}"
            storageSize: "${{ parameters.storageSize }}"
            dataConnectionName: "${{ parameters.dataConnectorName | parseEntityRef | pick('name') }}"
            enabledCUDA: ${{ parameters.enableCUDA }}
            numGPU: "${{ parameters.numGPU }}"

    ##############
    ## Rename File
    ##############
    - id: changeTemplateName
      name: Change Template Name
      action: fs:rename
      input:
        files:
          - from: "projects/${{ parameters.projectName | parseEntityRef | pick('name') }}/application.yaml"
            to: "projects/${{ parameters.projectName | parseEntityRef | pick('name') }}/${{ parameters.workbenchName }}-workbench.yaml"

    ##########################
    ## Push Repository Changes
    ##########################
    - id: publishManifests
      name: Publishing to the Source Code Repository
      action: gitlab:repo:push
      input:
        allowedHosts:
          - ${{ steps['fetchSelfServiceEntity'].output.entity.spec.gitlab.instance }}
        description: |
          placeholder
        repoUrl: ${{ steps['fetchSelfServiceEntity'].output.entity.spec.gitlab.instance }}?owner=${{ steps['fetchSelfServiceEntity'].output.entity.spec.gitlab.owner }}&repo=${{ steps['fetchSelfServiceEntity'].output.entity.spec.gitlab.repository }}
        branchName: ${{ steps['fetchSelfServiceEntity'].output.entity.spec.gitlab.branch }}
        commitAction: create
        commitMessage: "Created ${{ parameters.workbenchName }} Workbench"

  output:
    links:
      - title: GitOps Application
        url: https://${{ steps['fetchSelfServiceEntity'].output.entity.spec.argocd.url }}/applications/openshift-gitops/root-self-service
      - title: GitLab Repository
        url: https://${{ steps['fetchSelfServiceEntity'].output.entity.spec.gitlab.instance }}/${{ steps['publishManifests'].output.projectPath }}