apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workshop-orchestrator
spec:
  generators:
    - list:
        elements:
          - application: workshop-rollout-controller
            namespace: openshift-gitops
            project: controllers
            wave: "-2"
            source: |
              chart: rollout-controller
              targetRevision: "0.6.78"
              repoURL: https://poc-examples.github.io/charts
              helm:
                values: |
                  controller:
                    name: workshop
                  devspaces:
                    enabled: true
                    enableCapacity: ${{ values.devspaces.enableCapacity }}
                    count: ${{ values.devspaces.count }}
                    sku: ${{ values.devspaces.sku }}
                  amq:
                    enabled: true
                    enableCapacity: ${{ values.amq.enableCapacity }}
                    count: ${{ values.amq.count }}
                    sku: ${{ values.amq.sku }}
                  opentelemetry:
                    enabled: true
                  minio:
                    enabled: true
                  serverless: 
                    enabled: true
                  cluster:
                    domain: ${{ values.cluster.domains.local }}
                    type: ${{ values.cluster.type }}
