apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  namespace: default
  name: resource-configs
  description: Resource configurations
spec:
  type: url
  owner: devops-team
  targets:
    - resources.yaml
