apiVersion: backstage.io/v1alpha1
kind: ${{ parameters.entityKind | default('Component') }}
metadata:
  name: ${{ parameters.repoName }}
  title: ${{ parameters.title | default('') }}
  description: ${{ parameters.description | default('') }}
  annotations:
    argocd/app-name: ${{ parameters.repoName }}
    backstage.io/techdocs-ref: dir:.
    ${{ parameters.sourceControl | toLowerCase() }}.com/project-slug: ${{ parameters.orgName }}/${{ parameters.repoName }}
spec:
  system: ${{ parameters.system | default('') }}
  lifecycle: ${{ parameters.lifecycle | default('production') }}
  owner: ${{ parameters.owner }}
  dependsOn:
    - ${{ parameters.dependsOn | default('') }}
  partOf:
    - ${{ parameters.partOf | default('') }}