apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: cpp-webserver
  title: Create a CPP website in GitLab with Tekton Pipelines
  description: Create a starter CPP website in GitLab with a Tekton Pipeline
  tags:
    - recommended
    - cpp
    - crow
    - gitlab
spec:
  owner: christopher-engleby
  system: poc-examples
  type: service

  parameters:
    - title: Provide information about the new component
      required:
        - orgName
        - repoName
        - owner
        - system
        - port
      properties:
        orgName:
          title: Organization Name
          default: "self-provisioned"
          type: string
        repoName:
          title: Repository Name
          type: string
        description:
          title: Description
          type: string
          description: Help others understand what this component provides
        owner:
          title: Owner
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - Group
                - User
        system:
          title: System
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - System
        port:
          title: Port
          type: number
          default: 8080
          description: Override the port exposed for the application

  steps:

    - id: sourceCodeTemplate
      name: Generating Source Code from Container Library
      action: fetch:template
      input:
        url: './skeleton'
      values:
        port: ${{ parameters.port }}

    - id: catalogTemplate
      name: Generating the Catalog Info Component
      action: fetch:template
      input:
        url: ../../skeletons/catalog-info/
        values:
          orgName: ${{ parameters.orgName }}
          repoName: ${{ parameters.repoName }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          applicationType: api
          description: ${{ parameters.description }}
          port: ${{ parameters.port }}
          sourceControl: gitlab.com

    - id: publish
      name: Publishing to the Source Code Repository
      action: publish:gitlab
      input:
        allowedHosts: ['gitlab.com']
        description: ${{ parameters.description }}
        repoUrl: gitlab.com?owner=${{ parameters.orgName }}&repo=${{ parameters.repoName }}
        defaultBranch: main

    - id: register
      name: Registering the Catalog Info Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Open the Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open the Catalog Info Component
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
