apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: Kafka Instance
  annotations:
    argocd/app-selector: backstage-name=${{ values.name }}
  tags:
    - kafka-instance
  links:
    - url: https://devspaces.apps.${{ values.devspaces.domain }}#${{ values.gitlabRemoteUrl }}
      title: "DevSpaces: Open Deployment Manifests"
      icon: web
spec:
  type: kafka-instance
  lifecycle: production
  owner: ${{ values.owner }}
  dependsOn:
    - ${{ values.rootSelfServiceRepo }}
  kafka:
    brokerService: ${{ values.brokerService }}
    bootstrapService: ${{ values.bootstrapService }}
