apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "sync-root-projects"
  namespace: "openshift-gitops"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: "openshift-gitops"
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: "${{ values.repoUrl }}"
    targetRevision: "main"
    path: "projects"
    directory:
      recurse: true
  project: "self-service"
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: "openshift-gitops"
    syncOptions:
      - CreateNamespace=true
      - Validate=false
      - SkipDryRunOnMissingResource=true
