apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "sync-root-projects"
  namespace: "openshift-gitops"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: "openshift-gitops"
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: "${{ values.app.repoUrl }}"
    targetRevision: "${{ values.app.targetRevision }}"
    path: "${{ values.app.path }}"
    directory:
      recurse: true
  project: ${{ values.projectName }}
  syncPolicy:
    automated:
      {%- if values.automated.prune %}
      prune: "${{ values.automated.prune }}"
      {%- endif %}
      {%- if values.automated.selfHeal %}
      selfHeal: "${{ values.automated.selfHeal }}"
      {%- endif %}
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: "openshift-gitops"
    syncOptions:
      {%- if values.createNamespace %}
      - CreateNamespace=${{ values.createNamespace }}
      {%- endif %}
      - Validate=false
      - SkipDryRunOnMissingResource=true