apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: gitlab-self-service-repository
  title: Create a GitLab Self-Service Repository
  description: |
    This template automates the creation of a GitLab repository from a predefined skeleton,
    and sets up an ArgoCD application to synchronize changes from the repository automatically.
    It simplifies the process of integrating GitLab and ArgoCD, enabling self-service repository
    creation with seamless continuous deployment capabilities.
  tags:
    - gitlab
    - argocd
    - automation
    - devops
spec:
  owner: devops-team
  system: poc-examples
  type: ci-cd-integration

  parameters:
    - title: General Application Information
      ui:group: general
      required:
        - appName
        - repoUrl
      properties:
        appName:
          title: Application Name
          description: The name of the application to be created in ArgoCD.
          type: string
        repoUrl:
          title: Repository Url
          description: The URL of the GitLab repository that contains the application source code.
          type: string

    - title: ArgoCD Configuration
      ui:group: argocd
      required:
        - argoInstance
        - namespace
        - path
      properties:
        namespace:
          title: Application Namespace
          description: The Kubernetes namespace where the application will be deployed.
          type: string
        argoInstance:
          title: ArgoCD Instance
          description: The ArgoCD instance where the application will be deployed. Select from the available options.
          enum:
            - main
          type: string
        path:
          title: ArgoCD Path Field
          description: The path in the repository that contains the ArgoCD manifests.
          type: string

  steps:

    ######################################
    ## Test ArgoCD Resources Configuration
    ######################################
    - id: create-argocd-resources
      name: Create ArgoCD Resources
      action: argocd:create-resources
      input:
        appName: ${{ parameters.appName }}
        argoInstance: ${{ parameters.argoInstance }}
        namespace: ${{ parameters.namespace }}
        repoUrl: ${{ parameters.repoUrl }}
        path: ${{ parameters.path }}

  output:
    links:
      - title: Application
        url: https://argocd-instance/${{ parameters.argoInstance }}/applications/${{ parameters.appName }}
      - title: ArgoCD Instance
        icon: catalog
        url: https://argocd-instance/${{ parameters.argoInstance }}
