apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: gitlab-self-service-repository
  title: Create a GitLab Self-Service Repository
  description: |
    This template automates the creation of a GitLab repository from a predefined skeleton,
    and sets up an ArgoCD application to synchronize changes from the repository automatically.
    It simplifies the process of integrating GitLab and ArgoCD, enabling self-service repository
    creation with seamless continuous deployment capabilities.
  tags:
    - gitlab
    - argocd
    - automation
    - devops
spec:
  owner: devops-team
  system: poc-examples
  type: ci-cd-integration

  parameters:
    - title: Provide information about the new ArgoCD Resource
      required:
        - appName
        - argoInstance
        - namespace
        - repoUrl
        - labelValue
        - path
      properties:
        appName:
          title: Application Name
          description: add this
          type: string
        argoInstance:
          title: ArgoCD Instance
          description: add this
          enum:
            - main
          type: string
        namespace:
          title: Application Namespace
          description: add this
          type: string
        repoUrl:
          title: Repository Url
          description: add this
          type: string
        # labelValue:
        #   title: Owner
        #   description: add this
        #   type: string
        #   ui:field: EntityPicker
        #   ui:options:
        #     catalogFilter:
        #       kind:
        #         - Group
        #         - User
        path:
          title: ArgoCD Path Field
          description: add this
          type: string

  steps:

    ######################################
    ## Test ArgoCD Resources Configuration
    ######################################
    - id: create-argocd-resources
      name: Create ArgoCD Resources
      action: argocd:create-resources
      input:
        appName: ${{ parameters.name }}
        argoInstance: ${{ parameters.argoinstance }}
        namespace: ${{ parameters.namespace }}
        repoUrl: ${{ parameters.remoteUrl }}
        # labelValue: ${{ parameters.name }}
        path: ${{ parameters.path }}

  output:
    links:
      - title: Application
        url: https://argocd-instance/${{ parameters.argoinstance }}/applications/${{ parameters.appName }}
      - title: ArgoCD Instance
        icon: catalog
        entityRef: ${{ parameters.argoinstance }}
