apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: single-model-server
  title: Red Hat OpenShift AI - Single Model Server
  description: |
    This template automates the deployment of a Single Model Server in Red Hat OpenShift AI. 
    It provides a scalable environment for serving a single AI/ML model, allowing teams to 
    quickly launch, manage, and scale their AI models in production. The template ensures 
    seamless integration with OpenShift AI services, offering support for continuous 
    deployment, model monitoring, and version management. Ideal for projects focused on 
    deploying one model at a time with optimized resources.
  tags:
    - openshift-ai
    - model-serving
    - automation
    - ai-workloads
    - mlops
    - argocd

spec:
  owner: data-science
  system: self-service
  type: Single-Model-Server
  parameters:

    - title: Model Serving Settings
      ui:group: data-model-serving
      required:
        - rootSelfServiceRepo
        - projectName
        - modelName
      properties:
        rootSelfServiceRepo:
          title: Root Self-Service Repository
          type: string
          description: The root self-service repository that contains artifact deployment configurations.
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              - kind: Component
                spec.type: self-service
        projectName:
          title: Project Name
          type: string
          description: The project where the data connector is integrated.
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              - kind: Component
                spec.type: data-science-project
        numGPU:
          title: Number of GPU
          description: The Number of GPUs to provide to running model.
          default: 1
          type: number
          enum:
            - 0
            - 1
            - 2
            - 3
            - 4
        memoryLimit:
          title: Memory Limit
          description: The Memory Limit for the running model(Mi,Gi).
          type: string
          default: "35Gi"
        cpuLimit:
          title: CPU Limit
          description: The CPU Limit for the running model(1000m).
          type: string
          default: "1000m"
        modelName:
          title: Model Name
          description: The name of the Model.
          type: string
          pattern: "^[a-z][a-z0-9-]+$"
          minLength: 3
          maxLength: 30

    - title: Model Serving Settings
      ui:group: data-model-serving
      required:
        - dataConnectorName
        - modelPath
      properties:
        dataConnectorName:
          title: Data Connector Name
          description: The name of the data connector.
          type: string
          pattern: "^[a-z][a-z0-9-]+$"
          minLength: 3
          maxLength: 30
        modelPath:
          title: Model Path
          description: The path to the Model in Data Connector.
          type: string

  steps:

    #################
    ## Fetch Entities
    #################

    - action: catalog:fetch
      id: fetchSelfServiceEntity
      name: Fetch Root Self-Service Repo Entity
      input:
        entityRef: ${{ parameters.rootSelfServiceRepo }}

    ###########################
    ## Template the Application
    ###########################
    - id: applicationTemplate
      name: Template Helm Application:template
      action: fetch:template
      input:
        url: "../../../../skeletons/applications/helm/"
        targetPath: "projects/${{ parameters.projectName }}/"
        values:
          repoName: "${{ parameters.modelName }}-model-server"
          namespace: "${{ parameters.projectName }}"
          chart:
            name: "data-single-model-server"
            chartUrl: "https://poc-examples.github.io/supporting-charts"
            chartVersion: "0.1.1"
          projectName: "${{ parameters.projectName }}"
          automated:
            prune: true
            selfHeal: true
          createNamespace: "true"
          valuesObject: |
            serviceName: ${{ parameters.modelName }}
            servingRuntime: multi-gpu-vllm-runtime
            replicas: 1
            GPUCount: ${{ parameters.numGPU }}
            dataConnection:
              name: ${{ parameters.dataConnectorName }}
              modelPath: ${{ parameters.modelPath }}
            resources:
              cpu: "${{ parameters.cpuLimit }}"
              mem: "${{ parameters.memoryLimit }}"

    ##############
    ## Rename File
    ##############
    - id: changeTemplateName
      name: Change Template Name
      action: fs:rename
      input:
        files:
          - from: "projects/${{ parameters.projectName }}/application.yaml"
            to: "projects/${{ parameters.projectName }}/${{ parameters.modelName }}-model-server.yaml"

    ##########################
    ## Push Repository Changes
    ##########################
    - id: publishManifests
      name: Publishing to the Source Code Repository
      action: gitlab:repo:push
      input:
        allowedHosts:
          - 'gitlab.com'
        description: |
          placeholder
        repoUrl: gitlab.com?owner=self-provisioned&repo=manifests
        sourcePath: "./projects/${{ parameters.projectName }}"
        targetPath: "./projects/${{ parameters.projectName }}"
        branchName: main
        commitAction: create
        commitMessage: "Created ${{ parameters.modelName }} Model Server"

    ########################
    ## Register Catalog Info
    ########################
    - id: registerCatalog
      name: "Register Catalog Info"
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps["publishManifests"].output.repoContentsUrl }}
        catalogInfoPath: /model-server-entity.yaml

  output:
    links:
      - title: GitOps Application
        url: https://${{ steps['fetchSelfServiceEntity'].output.entity.spec.argocd.url }}/applications/openshift-gitops/root-self-service
      - title: GitLab Repository
        url: https://${{ steps['fetchSelfServiceEntity'].output.entity.spec.gitlab.instance }}/${{ steps['publishManifests'].output.projectPath }}