helmCharts:
  - name: "kafka-instance"
    repo: "https://poc-examples.github.io/supporting-charts"
    version: "0.0.4"
    namespace: "${{ values.name }}-kafka"
    valuesInline:
      name: ${{ values.name }}-instance
      userName: ${{ values.name }}
